version: 2
jobs:
  build-api-feed:
    steps:
      - run:
          name: Build Docker image
          command: docker build -t udagram-api-feed ./udagram-api-feed
      - run:
          name: Tagging
          command: docker tag udagram-api-feed vhthieu100499/udagram-api-feed:v1
      - run:
          name: Push
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            - docker push vhthieu100499/udagram-api-feed:v1
  build-api-user:
    steps:
      - run:
          name: Build Docker image
          command: docker build -t udagram-api-user ./udagram-api-user
      - run:
          name: Tagging
          command: docker tag udagram-api-user vhthieu100499/udagram-api-user:v1
      - run:
          name: Push
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push vhthieu100499/udagram-api-user:v1
  build-frontend:
    steps:
      - run:
          name: Build Docker image
          command: docker build -t udagram-frontend ./udagram-frontend
      - run:
          name: Tagging
          command: docker tag udagram-frontend vhthieu100499/udagram-frontend:v1
      - run:
          name: Push
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push vhthieu100499/udagram-frontend:v1
  build-reverseproxy:
    steps:
      - run:
          name: Build Docker image
          command: docker build -t udagram-reverseproxy ./udagram-reverseproxy
      - run:
          name: Tagging
          command: docker tag udagram-reverseproxy vhthieu100499/udagram-reverseproxy:v1
      - run:
          name: Push
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push vhthieu100499/udagram-reverseproxy:v1
workflows:
  version: 2
  build-master:
    jobs:
      - build-api-feed:
          filters:
            branches:
              only: master
      - build-api-user:
          requires:
            - build-api-feed
          filters:
            branches:
              only: master
      - build-frontend:
          requires:
            - build-api-user
          filters:
            branches:
              only: master
      - build-reverseproxy:
          requires:
            - build-frontend
          filters:
            branches:
              only: master